# Generated by Django 5.2 on 2025-11-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
